# Generated by Django 4.2 on 2023-04-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
